version: '3.8'

services:
  app:
    build: .
    container_name: biblioteca-virtual
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/opt/jboss/wildfly/standalone/logs_bibliotecavirtual
    environment:
      HOST: db_postgres
      NAME: bibliotecaVirtual
      USER: postgres
      PASSWORD: "TEznl41B*"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: db_postgres
    environment:
      POSTGRES_DB: bibliotecaVirtual
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "TEznl41B*"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
